name: Backend Sonar Pipeline
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        with:
          projectBaseDir: ./back
        uses: mvn sonar:sonar

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}