name: BoB Backend Docker Build and Push image Pipeline

on:
  workflow_call:
  push:

jobs:
    build-backend:
      uses: ./.github/workflows/backend-pipeline.yml

    build:
      runs-on: ubuntu-latest
      needs: [build-backend]
      steps:
        - name: Checkout repo --> downloading the code resource
          uses: actions/checkout@v4

        - name: Setup JDK 11
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven

        - name: Build Docker Image
          uses: docker/build-push-action@v5
          with:
              context: ./back
              file: ./back/Dockerfile
              push: false
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob-backend-api:lastest

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Push Docker Image to Docker Hub
          uses: docker/build-push-action@v5
          with:
              context: ./back
              file: ./back/Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob-backend-api:lastest