name: BoB Frontend Docker Build and Push image Pipeline

on:
  workflow_call:
  push:

jobs:
    build-backend:
      uses: ./.github/workflows/frontend-pipeline.yml

    build:
      runs-on: ubuntu-latest
      needs: [build-backend]
      steps:
        - name: Checkout repo --> downloading the code resource
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 14
            cache: 'npm'
            cache-dependency-path: front/package-lock.json

        - name: Build Docker Image
          uses: docker/build-push-action@v5
          with:
              context: ./front
              file: ./front/Dockerfile
              push: false
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob-frontend:lastest

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Push Docker Image to Docker Hub
          uses: docker/build-push-action@v5
          with:
              context: ./back
              file: ./back/Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob-frontend:lastest