name: BoB Frontend Pipeline

on:
  workflow_call:

  push:
    branches:
      - main
      - develop
    paths:
      - front/**
      - .github/workflows/frontend-pipeline.yml
      - .github/workflows/docker-build-push-frontend.yml

  pull_request:
    branches:
      - main

jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo --> downloading the code resource
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 14
            cache: 'npm'
            cache-dependency-path: front/package-lock.json

        - name: Install dependencies
          run: |
            cd front
            npm ci

        - name: Build with npm
          run: |
            cd front
            npm run build

    unit-test:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo --> downloading the code resource
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 14
            cache: 'npm'
            cache-dependency-path: front/package-lock.json

        - name: Install dependencies
          run: |
            cd front
            npm ci

        - name: Run unit tests and Generate test coverage report
          run: |
            cd front
            npm run test:ci

    test-report:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo --> downloading the code resource
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 14
                cache: 'npm'
                cache-dependency-path: front/package-lock.json

            - name: Install dependencies
              id: karma_reporter
              run: |
                cd front
                npm ci
                npm run test:ci

            - name: Upload test coverage report
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: front/coverage/bobapp
                retention-days: 1

            - name: Get the Coverage info
              run: |
                echo "Coverage: ${{ steps.karma_reporter.outputs.coveragePercentage }}%"
                echo "Coverage summary: ${{ steps.karma_reporter.outputs.coverageSummary }}"